package backend;

import java.io.BufferedReader;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

import database.TransactionDAO;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

/**
 * Handles processing checkout transactions by receiving a sales session payload,
 * persisting data to the database, and building a thermal layout receipt PDF document.
 */
@WebServlet(name = "CheckoutServlet", urlPatterns = "/checkout")
public class CheckoutServlet extends HttpServlet {

    private static final Logger LOGGER = Logger.getLogger(CheckoutServlet.class.getName());

    private static final float RECEIPT_WIDTH_PT  = 226f;  // 80mm standard width profile
    private static final float MARGIN_PT         = 12f;

    private static final String STORE_NAME    = "BillDesk Store";
    private static final String STORE_ADDRESS = "123 Main Road, Ranchi, JH 834001";
    private static final String STORE_PHONE   = "+91 98765 43210";
    private static final String STORE_GSTIN   = "20AABCU9603R1ZP";

    private final TransactionDAO transactionDAO = new TransactionDAO();

    /**
     * Processes incoming POST requests to compile transactions, save record sets to MySQL,
     * and stream generated byte content back over the active HTTP network stream connection response channel.
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws IOException {

        String jsonBody = readRequestBody(request);

        if (jsonBody == null || jsonBody.trim().isEmpty()) {
            sendError(response, HttpServletResponse.SC_BAD_REQUEST, "Empty request body.");
            return;
        }

        CheckoutPayload payload;
        try {
            payload = parsePayload(jsonBody);
        } catch (Exception e) {
            LOGGER.log(Level.WARNING, "Failed to parse checkout JSON: " + jsonBody, e);
            sendError(response, HttpServletResponse.SC_BAD_REQUEST, "Invalid JSON payload: " + e.getMessage());
            return;
        }

        if (payload.items.isEmpty()) {
            sendError(response, HttpServletResponse.SC_BAD_REQUEST, "Cart is empty — nothing to checkout.");
            return;
        }

        // Updated to explicitly push profile parameters down to the persistence layer map boundary
        Map<String, Object> transactionData = new HashMap<>();
        transactionData.put("customerName",  payload.customerName);
        transactionData.put("customerEmail", payload.customerEmail);
        transactionData.put("subtotal",      payload.subtotal);
        transactionData.put("discount",      payload.discount);
        transactionData.put("taxAmount",     payload.taxAmount);
        transactionData.put("grandTotal",    payload.grandTotal);

        List<Map<String, Object>> itemMaps = new ArrayList<>();
        for (ItemPayload item : payload.items) {
            Map<String, Object> m = new HashMap<>();
            m.put("productUid",     item.productUid);
            m.put("productName",    item.productName);
            m.put("basePrice",      item.basePrice);
            m.put("quantity",       item.quantity);
            m.put("taxRate",        item.taxRate);
            m.put("discountPct",    item.discountPct);
            m.put("calculatedTax",  item.calculatedTax);
            m.put("finalItemPrice", item.finalItemPrice);
            itemMaps.add(m);
        }

        boolean saved = transactionDAO.saveTransaction(transactionData, itemMaps);

        if (!saved) {
            sendError(response, HttpServletResponse.SC_INTERNAL_SERVER_ERROR, "Failed to save transaction. Please try again.");
            return;
        }

        LOGGER.info("Transaction saved. Generating receipt PDF for " + payload.items.size() + " item(s).");

        byte[] pdfBytes;
        try {
            pdfBytes = buildPdf(payload);
        } catch (DocumentException e) {
            LOGGER.log(Level.SEVERE, "PDF generation failed after successful DB save.", e);
            sendError(response, HttpServletResponse.SC_INTERNAL_SERVER_ERROR, "Sale saved successfully but receipt could not be generated.");
            return;
        }

        // ══════════════ INSERT EMAIL MODULE HERE ══════════════
        if (payload.customerEmail != null && !payload.customerEmail.trim().isEmpty()) {
            String cleanFileName = "Receipt_" + System.currentTimeMillis() + ".pdf";
            EmailService.sendReceiptEmail(
                payload.customerEmail.trim(), 
                payload.customerName, 
                pdfBytes, 
                cleanFileName
            );
        }
        // ══════════════════════════════════════════════════════

        // ─── GENERATE FILENAME DYNAMICALLY WITH DATE & TIME ───
        LocalDateTime currentDateTime = LocalDateTime.now();
        DateTimeFormatter fileDateTimeFormatter = DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss");
        String formattedTimestamp = currentDateTime.format(fileDateTimeFormatter);
        
        // Final layout output matches string requirement structural standard
        String uniqueReceiptName = "Receipt-Billing-System " + formattedTimestamp + ".pdf";

        response.setContentType("application/pdf");
        response.setContentLength(pdfBytes.length);
        response.setHeader("Content-Disposition", "inline; filename=\"" + uniqueReceiptName + "\"");
        response.setHeader("Cache-Control", "no-store");

        try (OutputStream out = response.getOutputStream()) {
            out.write(pdfBytes);
            out.flush();
        }
    }
    
    /**
     * Builds the receipt document layout using the iText PDF engine.
     * Computes height dynamically based on item lines and optional customer fields.
     */
    private byte[] buildPdf(CheckoutPayload payload) throws DocumentException, IOException {
        float headerHeight  = 145f;
        
        // Dynamically adjust canvas footprint based on metadata availability
        if (payload.customerName != null && !payload.customerName.isEmpty()) {
            headerHeight += 12f;
        }
        if (payload.customerEmail != null && !payload.customerEmail.isEmpty()) {
            headerHeight += 12f;
        }
        
        float itemHeight    = 28f;
        float summaryHeight = 100f;
        float footerHeight  = 40f;
        float totalHeight   = headerHeight + (payload.items.size() * itemHeight) + summaryHeight + footerHeight;

        Rectangle pageSize = new Rectangle(RECEIPT_WIDTH_PT, totalHeight);

        Font fontHeader   = FontFactory.getFont(FontFactory.HELVETICA_BOLD,  9f, BaseColor.BLACK);
        Font fontSubHeader= FontFactory.getFont(FontFactory.HELVETICA,       7f, BaseColor.DARK_GRAY);
        Font fontBody     = FontFactory.getFont(FontFactory.HELVETICA,       7.5f, BaseColor.BLACK);
        Font fontTotal    = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10f, BaseColor.BLACK);
        Font fontMuted    = FontFactory.getFont(FontFactory.HELVETICA,       7f,  new BaseColor(100,100,100));

        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        Document doc = new Document(pageSize, MARGIN_PT, MARGIN_PT, MARGIN_PT, MARGIN_PT);
        PdfWriter.getInstance(doc, baos);
        doc.open();

        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd-MM-yyyy  HH:mm:ss");
        String timestamp = LocalDateTime.now().format(dtf);

        addCenteredParagraph(doc, STORE_NAME,    fontHeader,   6f);
        addCenteredParagraph(doc, STORE_ADDRESS, fontSubHeader, 2f);
        addCenteredParagraph(doc, "Ph: " + STORE_PHONE, fontSubHeader, 2f);
        addCenteredParagraph(doc, "GSTIN: " + STORE_GSTIN, fontSubHeader, 2f);
        addCenteredParagraph(doc, timestamp,     fontMuted,    4f);
        
        // Append customer info lines if provided in payload
        if (payload.customerName != null && !payload.customerName.isEmpty()) {
            addCenteredParagraph(doc, "Customer: " + payload.customerName, fontSubHeader, 2f);
        }
        if (payload.customerEmail != null && !payload.customerEmail.isEmpty()) {
            addCenteredParagraph(doc, "Email: " + payload.customerEmail, fontSubHeader, 2f);
        }
        
        addDivider(doc);

        PdfPTable itemTable = new PdfPTable(2);
        itemTable.setWidthPercentage(100);
        itemTable.setWidths(new float[]{65f, 35f});
        itemTable.setSpacingBefore(4f);
        itemTable.setSpacingAfter(4f);

        for (ItemPayload item : payload.items) {
            String itemLabel = item.quantity + "\u00D7 " + item.productName;
            PdfPCell leftCell = new PdfPCell(new Phrase(itemLabel, fontBody));
            leftCell.setBorder(Rectangle.NO_BORDER);
            leftCell.setPaddingBottom(3f);

            String priceLabel = "Rs. " + String.format("%.2f", item.finalItemPrice);
            PdfPCell rightCell = new PdfPCell(new Phrase(priceLabel, fontBody));
            rightCell.setBorder(Rectangle.NO_BORDER);
            rightCell.setHorizontalAlignment(Element.ALIGN_RIGHT);
            rightCell.setPaddingBottom(3f);

            if (item.discountPct > 0 || item.taxRate > 0) {
                StringBuilder sub = new StringBuilder();
                sub.append("@ Rs.").append(String.format("%.2f", item.basePrice));
                if (item.discountPct > 0) sub.append("  disc ").append(item.discountPct).append("%");
                if (item.taxRate > 0)     sub.append("  tax ").append(item.taxRate).append("%");

                leftCell = new PdfPCell();
                leftCell.setBorder(Rectangle.NO_BORDER);
                leftCell.setPaddingBottom(3f);
                Paragraph p = new Paragraph();
                p.add(new Chunk(itemLabel + "\n", fontBody));
                p.add(new Chunk(sub.toString(), fontMuted));
                leftCell.addElement(p);
            }

            itemTable.addCell(leftCell);
            itemTable.addCell(rightCell);
        }

        doc.add(itemTable);
        addDivider(doc);

        PdfPTable summaryTable = new PdfPTable(2);
        summaryTable.setWidthPercentage(100);
        summaryTable.setWidths(new float[]{55f, 45f});
        summaryTable.setSpacingBefore(4f);

        addSummaryRow(summaryTable, "Subtotal",    "Rs. " + fmt(payload.subtotal),   fontBody, fontBody);
        addSummaryRow(summaryTable, "Discount",    "- Rs. " + fmt(payload.discount), fontBody, fontBody);
        addSummaryRow(summaryTable, "Tax (GST)",   "+ Rs. " + fmt(payload.taxAmount),fontBody, fontBody);
        doc.add(summaryTable);

        addThickDivider(doc);

        PdfPTable grandTable = new PdfPTable(2);
        grandTable.setWidthPercentage(100);
        grandTable.setWidths(new float[]{50f, 50f});
        grandTable.setSpacingBefore(4f);
        grandTable.setSpacingAfter(6f);
        addSummaryRow(grandTable, "GRAND TOTAL", "Rs. " + fmt(payload.grandTotal), fontTotal, fontTotal);
        doc.add(grandTable);

        addThickDivider(doc);

        addCenteredParagraph(doc, "Thank you for shopping!", fontMuted, 6f);
        addCenteredParagraph(doc, "Please visit again.",     fontMuted, 2f);

        doc.close();
        return baos.toByteArray();
    }

    /**
     * Parses the raw JSON string payload received from the frontend into structured data objects.
     */
    private CheckoutPayload parsePayload(String json) {
        JsonObject root = JsonParser.parseString(json).getAsJsonObject();

        CheckoutPayload payload  = new CheckoutPayload();
        
        // Securely pull optional custom string tags safely without breaking basic guest checkouts
        if (root.has("customer") && !root.get("customer").isJsonNull()) {
            JsonObject customer = root.getAsJsonObject("customer");
            JsonElement nameEl = customer.get("name");
            payload.customerName = (nameEl != null && !nameEl.isJsonNull()) ? nameEl.getAsString() : null;
            JsonElement emailEl = customer.get("email");
            payload.customerEmail = (emailEl != null && !emailEl.isJsonNull()) ? emailEl.getAsString() : null;
        }

        payload.subtotal   = getDouble(root, "subtotal");
        payload.discount   = getDouble(root, "discount");
        payload.taxAmount  = getDouble(root, "taxAmount");
        payload.grandTotal = getDouble(root, "grandTotal");

        JsonArray itemsArray = root.getAsJsonArray("items");
        if (itemsArray == null) {
            throw new IllegalArgumentException("'items' array is missing from payload.");
        }

        for (JsonElement el : itemsArray) {
            JsonObject obj = el.getAsJsonObject();
            ItemPayload item = new ItemPayload();
            item.productUid     = getString(obj, "productUid");
            item.productName    = getString(obj, "productName");
            item.basePrice      = getDouble(obj, "basePrice");
            item.quantity       = getInt(obj,    "quantity");
            item.taxRate        = getDouble(obj, "taxRate");
            item.discountPct    = getDouble(obj, "discountPct");
            item.calculatedTax  = getDouble(obj, "calculatedTax");
            item.finalItemPrice = getDouble(obj, "finalItemPrice");
            payload.items.add(item);
        }

        return payload;
    }

    private static class CheckoutPayload {
        String customerName;
        String customerEmail;
        double subtotal;
        double discount;
        double taxAmount;
        double grandTotal;
        List<ItemPayload> items = new ArrayList<>();
    }

    private static class ItemPayload {
        String productUid;
        String productName;
        double basePrice;
        int    quantity;
        double taxRate;
        double discountPct;
        double calculatedTax;
        double finalItemPrice;
    }

    /** Reads the total body character buffer stream from the HTTP request channel. */
    private String readRequestBody(HttpServletRequest request) throws IOException {
        StringBuilder sb = new StringBuilder();
        try (BufferedReader reader = request.getReader()) {
            String line;
            while ((line = reader.readLine()) != null) {
                sb.append(line);
            }
        }
        return sb.toString();
    }

    /** Dispatches structured JSON formatted error payloads back to the response interface. */
    private void sendError(HttpServletResponse response, int status, String message)
            throws IOException {
        response.setStatus(status);
        response.setContentType("application/json");
        response.setCharacterEncoding("UTF-8");
        try (var writer = response.getWriter()) {
            writer.print("{\"error\":\"" + message.replace("\"", "'") + "\"}");
        }
    }

    private void addCenteredParagraph(Document doc, String text, Font font, float spacingAfter)
            throws DocumentException {
        Paragraph p = new Paragraph(text, font);
        p.setAlignment(Element.ALIGN_CENTER);
        p.setSpacingAfter(spacingAfter);
        doc.add(p);
    }

    private void addDivider(Document doc) throws DocumentException {
        Paragraph divider = new Paragraph("- - - - - - - - - - - - - - - - -", 
            FontFactory.getFont(FontFactory.HELVETICA, 7f, BaseColor.LIGHT_GRAY));
        divider.setAlignment(Element.ALIGN_CENTER);
        divider.setSpacingBefore(3f);
        divider.setSpacingAfter(3f);
        doc.add(divider);
    }

    private void addThickDivider(Document doc) throws DocumentException {
        Paragraph divider = new Paragraph("═══════════════════════════",
            FontFactory.getFont(FontFactory.HELVETICA, 7f, BaseColor.BLACK));
        divider.setAlignment(Element.ALIGN_CENTER);
        divider.setSpacingBefore(3f);
        divider.setSpacingAfter(3f);
        doc.add(divider);
    }

    private void addSummaryRow(PdfPTable table, String label, String value, Font labelFont, Font valueFont) {
        PdfPCell left = new PdfPCell(new Phrase(label, labelFont));
        left.setBorder(Rectangle.NO_BORDER);
        left.setPaddingBottom(3f);

        PdfPCell right = new PdfPCell(new Phrase(value, valueFont));
        right.setBorder(Rectangle.NO_BORDER);
        right.setHorizontalAlignment(Element.ALIGN_RIGHT);
        right.setPaddingBottom(3f);

        table.addCell(left);
        table.addCell(right);
    }

    private String fmt(double value) {
        return String.format("%.2f", value);
    }

    private double getDouble(JsonObject obj, String key) {
        JsonElement el = obj.get(key);
        if (el == null || el.isJsonNull()) {
            throw new IllegalArgumentException("Missing numeric field: '" + key + "'");
        }
        return el.getAsDouble();
    }

    private int getInt(JsonObject obj, String key) {
        JsonElement el = obj.get(key);
        if (el == null || el.isJsonNull()) {
            throw new IllegalArgumentException("Missing integer field: '" + key + "'");
        }
        return el.getAsInt();
    }

    private String getString(JsonObject obj, String key) {
        JsonElement el = obj.get(key);
        if (el == null || el.isJsonNull()) {
            throw new IllegalArgumentException("Missing string field: '" + key + "'");
        }
        return el.getAsString();
    }
}